language: php

dist: trusty

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

jobs:
    include:
        - stage: Code Quality
          php: 7.2
          env: STATIC_ANALYSIS
          install: travis_retry composer install --prefer-dist
          script: composer static-analysis
    allow_failures:
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - if [[ "$TRAVIS_PHP_VERSION" != "5.6" ]]; then phpenv config-rm xdebug.ini || true; fi
    - phpenv config-rm xdebug.ini || true
    - composer selfupdate

install: composer install --dev --prefer-dist

script: if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then bin/phpunit --coverage-clover build/logs/clover.xml --group default,ReactPromise; else bin/phpunit --group default,ReactPromise; fi

after_success:
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer require "satooshi/php-coveralls:^1.0" && travis_retry php bin/coveralls -v; fi
